package com.yourcompany.a11y.generator;

import com.yourcompany.a11y.model.A11yResult;
import com.yourcompany.a11y.model.ChartConfig;
import com.yourcompany.a11y.model.LocalizedDescription;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * Generator for Android string resource files containing accessibility descriptions.
 */
public class StringResourceGenerator {

    private static final String XML_HEADER = "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
    private static final String RESOURCES_OPEN = "<resources>";
    private static final String RESOURCES_CLOSE = "</resources>";
    private static final String COMMENT = "    <!-- Auto-generated by Chart A11y Plugin. Do not edit. -->";

    /**
     * Generate string resource files for the default values directory.
     *
     * @param outputDir the base output directory (e.g., build/generated/res/a11y/debug)
     * @param charts the list of chart configurations
     * @param results the map of chart ID to API results
     * @throws IOException if file writing fails
     */
    public void generate(File outputDir, List<ChartConfig> charts,
                         Map<String, A11yResult> results) throws IOException {
        File valuesDir = new File(outputDir, "values");
        valuesDir.mkdirs();

        File stringsFile = new File(valuesDir, "chart_a11y_strings.xml");
        generateStringsFile(stringsFile, charts, results);
    }

    private void generateStringsFile(File file, List<ChartConfig> charts,
                                     Map<String, A11yResult> results) throws IOException {
        try (PrintWriter writer = new PrintWriter(
                new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8))) {

            writer.println(XML_HEADER);
            writer.println(RESOURCES_OPEN);
            writer.println(COMMENT);

            for (ChartConfig chart : charts) {
                A11yResult result = results.get(chart.getId());
                if (result == null || !result.hasDescriptions()) {
                    continue;
                }

                LocalizedDescription desc = result.getForLocale("default");
                if (desc == null) {
                    desc = result.getForLocale("zh-CN");
                }
                if (desc == null) {
                    desc = result.getForLocale("en");
                }
                if (desc == null && result.getDescriptions() != null
                        && !result.getDescriptions().isEmpty()) {
                    desc = result.getDescriptions().values().iterator().next();
                }
                if (desc == null) {
                    continue;
                }

                String resourceName = chart.getResourceName();

                String description = desc.getBrief();
                if ((description == null || description.isEmpty())
                        && desc.getDetailed() != null && !desc.getDetailed().isEmpty()) {
                    description = desc.getDetailed();
                }

                if (description != null && !description.isEmpty()) {
                    writeStringResource(writer, "a11y_chart_" + resourceName, description);
                }

                // Write data point descriptions
                if (desc.getDataPoints() != null) {
                    for (int i = 0; i < desc.getDataPoints().size(); i++) {
                        String dataPoint = desc.getDataPoints().get(i);
                        if (dataPoint != null && !dataPoint.isEmpty()) {
                            writeStringResource(writer,
                                "a11y_chart_" + resourceName + "_point_" + i, dataPoint);
                        }
                    }
                }
            }

            writer.println(RESOURCES_CLOSE);
        }
    }

    private void writeStringResource(PrintWriter writer, String name, String value) {
        String escapedValue = escapeXml(value);
        writer.println("    <string name=\"" + name + "\">" + escapedValue + "</string>");
    }

    /**
     * Escape special characters for XML content.
     */
    private String escapeXml(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "\\'");
    }
}
