package com.yourcompany.a11y.generator;

import com.yourcompany.a11y.model.A11yResult;
import com.yourcompany.a11y.model.ChartConfig;
import com.yourcompany.a11y.model.LocalizedDescription;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

/**
 * Generator for Android string resource files containing accessibility descriptions.
 */
public class StringResourceGenerator {

    private static final String XML_HEADER = "<?xml version=\"1.0\" encoding=\"utf-8\"?>";
    private static final String RESOURCES_OPEN = "<resources>";
    private static final String RESOURCES_CLOSE = "</resources>";
    private static final String COMMENT = "    <!-- Auto-generated by Chart A11y Plugin. Do not edit. -->";

    /**
     * Generate string resource files for all locales.
     *
     * @param outputDir the base output directory (e.g., build/generated/res/a11y/debug)
     * @param charts the list of chart configurations
     * @param results the map of chart ID to API results
     * @param locales the list of locales to generate
     * @throws IOException if file writing fails
     */
    public void generate(File outputDir, List<ChartConfig> charts,
                         Map<String, A11yResult> results, List<String> locales) throws IOException {
        for (String locale : locales) {
            File valuesDir = getValuesDir(outputDir, locale);
            valuesDir.mkdirs();

            File stringsFile = new File(valuesDir, "chart_a11y_strings.xml");
            generateStringsFile(stringsFile, charts, results, locale);
        }
    }

    /**
     * Get the values directory for a locale.
     * Mapping rules:
     * - zh-CN -> values-zh-rCN
     * - en/en-US -> values (default)
     * - xx-YY -> values-xx-rYY
     */
    private File getValuesDir(File outputDir, String locale) {
        String dirName;
        if (locale == null || locale.isEmpty() || locale.equals("en") || locale.equals("en-US")) {
            dirName = "values";
        } else if (locale.contains("-")) {
            String[] parts = locale.split("-");
            dirName = "values-" + parts[0].toLowerCase() + "-r" + parts[1].toUpperCase();
        } else {
            dirName = "values-" + locale.toLowerCase();
        }
        return new File(outputDir, dirName);
    }

    private void generateStringsFile(File file, List<ChartConfig> charts,
                                     Map<String, A11yResult> results, String locale) throws IOException {
        try (PrintWriter writer = new PrintWriter(
                new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8))) {

            writer.println(XML_HEADER);
            writer.println(RESOURCES_OPEN);
            writer.println(COMMENT);

            for (ChartConfig chart : charts) {
                A11yResult result = results.get(chart.getId());
                if (result == null || !result.hasDescriptions()) {
                    continue;
                }

                LocalizedDescription desc = result.getForLocale(locale);
                if (desc == null) {
                    continue;
                }

                String resourceName = chart.getResourceName();

                // Write brief description
                if (desc.getBrief() != null && !desc.getBrief().isEmpty()) {
                    writeStringResource(writer, "a11y_chart_" + resourceName + "_brief", desc.getBrief());
                }

                // Write detailed description
                if (desc.getDetailed() != null && !desc.getDetailed().isEmpty()) {
                    writeStringResource(writer, "a11y_chart_" + resourceName + "_detailed", desc.getDetailed());
                }

                // Write data point descriptions
                if (desc.getDataPoints() != null) {
                    for (int i = 0; i < desc.getDataPoints().size(); i++) {
                        String dataPoint = desc.getDataPoints().get(i);
                        if (dataPoint != null && !dataPoint.isEmpty()) {
                            writeStringResource(writer,
                                "a11y_chart_" + resourceName + "_point_" + i, dataPoint);
                        }
                    }
                }
            }

            writer.println(RESOURCES_CLOSE);
        }
    }

    private void writeStringResource(PrintWriter writer, String name, String value) {
        String escapedValue = escapeXml(value);
        writer.println("    <string name=\"" + name + "\">" + escapedValue + "</string>");
    }

    /**
     * Escape special characters for XML content.
     */
    private String escapeXml(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "\\'");
    }
}
